name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-下载代码
        uses: actions/checkout@v3

      - name: Setup pnpm-安装pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js-安装node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies-安装依赖
        run: pnpm install

      - name: Build-执行构建,生成静态文件
        run: pnpm run build

      - name: Deploy-自动化部署
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vitepress/dist
          # cname: example.com # if you have a custom domain
